name: ci

on:
  push:
    branches:
      - master
      - main
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Build MkDocs Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt install -y pngquant ghostscript

      - uses: abatilo/actions-poetry@v2
      - run: poetry install
      - name: Cache MkDocs build directory
        uses: actions/cache@v4
        with:
          path: ./build
          key: ${{ runner.os }}-mkdocs-build-${{ hashFiles('docs/**/*.md', 'mkdocs.yml') }}
          restore-keys: |
            ${{ runner.os }}-mkdocs-build-

      - name: Build Documentation with MkDocs
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}
          GH_TOKEN: ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}
        run: CI=true poetry run mkdocs gh-deploy --force

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: latex
          path: ./build
